### PR TITLE
Fix namespaces of updated microsoft azure packages.

### PR DESCRIPTION
**Pull request by LensArt**

### CODE REVIEW

**Comment by frankdejonge** [comment]
@olsgreen I think this looks pretty good, care to pitch in for the review?

**Comment by frankdejonge** [comment]
@LensArt could you remove the 5.4 php version for travis too? The azure sdk requires 5.5 minimum.

**Comment by LensArt** [comment]
Just removed it! People need to update their DI if they use the old namespaces.

**Comment by frankdejonge** [comment]
@LensArt I'm thinkig about merging this into a new repo, because it's essentially a new adapter.

**Comment by LensArt** [comment]
@frankdejonge That's a good idea I think! If you do that, the "microsoft/windowsazure" package version of this repo needs to be fixed 0.4.2 to fix the type hint bug.

**Comment by luxifer** [comment]
Hi, currently it's impossible to use azure through flysystem because the version `2012-02-12` in the azure php sdk `v0.4.2` is outdated and I get a 400 error.

Any update on this PR?

**Comment by Lifesnoozer** [comment]
Any updates on the new adapter?

**Pull request merged**
