### PR TITLE
Passing config to the Azure client

### PR DESCRIPTION
**Pull request by guiwoda**
The `Config $config` parameter was being ignored by this adapter. I based the implementation on the aws-s3 adapter and added just a few options that I found available in the `CreateBlobOptions` object.

I know, others are missing, but its a start!

Test added and manually tested against the real thing.

### CODE REVIEW

**Comment by guiwoda** [comment]
CS changed a lot of stuff... let me know if you want that commit reverted!

**Comment by fabianpimminger** [comment]
+1

would be really awesome to set ContentType properties!

**Comment by guiwoda** [comment]
Can we merge this one @frankdejonge?

**Comment by frankdejonge** [comment]
@guiwoda I'll merge this one in tomorrow, it needs some conflict resolving, currently fighting jetlag.

**Comment by guiwoda** [comment]
Let me know if I can be of any help!

**Comment by frankdejonge** [comment]
@guiwoda a rebase would be very helpful. Lemme know if that works out.

**Comment by guiwoda** [comment]
@frankdejonge done!

**Pull request merged**
