### PR TITLE
Emulate directories in listed contents

### PR DESCRIPTION
**Pull request by zaak**
Added an emulation for directories similar way like it was done in AWS-S3 adapter.

### CODE REVIEW

**Comment by zaak** [comment]
@frankdejonge any thoughts on this PR? It's just a proposal how directory support could be implemented (I could continue work if this approach is ok). I know it has some drawbacks (i.e. creating dummy blobs to represent directories), but I'm not sure if there's any other way to implement this.

**Comment by frankdejonge** [comment]
@zaak hey, it looks good. I'm just trying to verify if this is indeed the expected behaviour for Azure. If you've got any links backing this, that'd be brilliant. The code looks good, but I'm not one to blindly merge altered behaviour without checking the source, hope you understand.

**Comment by zaak** [comment]
@frankdejonge I absolutely understand. Just wanted to push this forward and open a discussion, as in current version "directories" don't work at all.
I'm not 100% sure this is the best solution to handle this though. I based on what I found around the net.
https://social.msdn.microsoft.com/forums/azure/en-us/0a184e05-1d20-4b37-9ce5-bee8a5b6d09c/how-to-create-sub-folder-inside-container-in-azure-storage
http://stackoverflow.com/questions/2619007/windows-azure-how-to-create-sub-directory-in-a-blob-container
https://azure.microsoft.com/en-us/documentation/articles/storage-php-how-to-use-blobs/

The problem is similar like in case of AWS-S3 (flat filesystem without directories per se), so I started a similar way like it works in S3 adapter.

**Comment by frankdejonge** [comment]
@zaak merged, thanks!

**Comment by zaak** [comment]
Hi @frankdejonge. Just to clarify: the directory emulation support is not complete yet. I think some operations still don't work properly (like deleting the directory). But soon I'll continue work using this approach.

Cheers!

**Comment by frankdejonge** [comment]
@zaak all help is welcome :+1:

**Pull request merged**
